spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30583976296-pbimqomq466ad4gv758pbirm8nodth2r.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: uCpDbuFPmKLaL34mUOo5
            client-secret: PjWwodbMHu
            redirect-uri: http://localhost:8080/api/oauth2/naver
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          kakao:
            client-id: e11d1eb3e890a7e2f1cf55cb264e8576
            client-secret: KXsoZhvapETq1FNaI69spgBqvtq6DFfP
            redirect-uri: http://localhost:8080/api/oauth2/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
